### ISSUE TITLE
dt * x_dot

### ISSUE THREAD

**Issue by v-borse** [v-borse/simulate-classify-plot#1]
Line #56 ,57
>> Also, it would be preferable that this function only returns x_dot and not dt * x_dot
--> VB: dt*x_dot is used to facilitate in coding the RK4 method as compared to x_dot

**Comment by v-borse** [comment]
Line#77,78,79_/simulate
>> if you know the final length of the vector, you should preallocate it. here:
-->VB: the values allocated in these arrrays are unrealistic having powers as ^-316
#    x = np.empty((num_steps + 1) * ntraj)

**Comment by v-borse** [comment]
Line#31_/classify
>>It is probably not necessary to return the _c and _r variables as it is easy to deduce them from ts with the command np.where
-->VB: Creation of these variables was made with an intention when classification is followed by calculation of probabilities and so as you said it can be deduced directly from ts

**Comment by thaos** [comment]
- [ ]  Udpate the filenames with comprehensible name. You can also number them to let us know in which order to run the files. For instance, 1_simulate_lorenz.py
- [ ] I still think *dt* should not be use as an argument of the function lorenz. Here is why:

1.  The is a distinction between  the (mathematical) definition of the Lorenz system and the way we solve it numerically (RK4). The *dt* is only related to RK4 and not to the Lorenz system in itself.
2. If *dt* in hidden in the lorenz function, it is harder for someone reading you code to compare your code to the usual RK4 formulation
3. Putting *dt* in the  lorenz only prevent you from having to write a couple of multiplications. It is not really a huge gain.

- [ ] Pre-allocating arrays *x*, *y*, *z*. I wanted you to reserve the memory space of x, y, v instead of appending a new element at each iteration. When you append, python potentially needs to look for a new memory space able that is able to store you data at each iteration. When you pre-allocate the space with np.empty, it only reserves the space which contains what was previously in memory. It does not matter since we will overwrite everything. I suggested to use np.empty because it is the function that you used for *xs*, *ys* and *zs*.
- [ ] Please removed comments that are now unneeded and also unused commented code.
