### ISSUE TITLE
Why is there two R_predict function ?

### ISSUE THREAD

**Issue by thaos** [v-borse/simulate-classify-plot#16]
https://github.com/v-borse/simulate-classify-plot/blob/8177637250f295b89abf7601cc8c7045ef33c862/testLN.py#L41-L84

1. in r_predict, you do unnecessary shape formating of the data. R_predict should work or at least with minimal modifications

2.  the predict functions should take rx, ry and rz  as input

**Comment by v-borse** [comment]
1. Initially tried to merge r_predict and R_predict because both take same arguments and return same array but if I don't reshape in r_predict it gives error (mismatch of shape of Xnew0 and Xnew[:, 0, None] ). Also I created these two functions separate so there is flexibility in selection since models are different
2. I would try this because probably this might lead to rectify some points in 1.

**Comment by thaos** [comment]
Have a look at my pull request #14 to see you can simplify the multivariate case.
It seems you have issues because you don't know when to Xnew[:, 0]   or Xnew[:, 0, None] . Use the former if you want the return shape to be (-1, ) and the latter if you want the shape to be (-1, 1).
Also often time, you use X[:, :] while you could simply X.

**Comment by thaos** [comment]
OK i understand the difference between the two function, one is for univariate cas, the other for the multivariate case. Please give a proper name to the function.
